Bugfix values function
Laravel-Backpack/CRUD pull request #3192
Opened 2020-09-09 09:47 UTC by mahasadhu

Values function in fluent api not calling the inner / callback / anonymous function sent to it as parameter

2020-09-09 09:47 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/7656b9d6-b65a-40b0-a4c8-0d44be1bc48b) was created.

2020-09-09 10:40 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/7656b9d6-b65a-40b0-a4c8-0d44be1bc48b) completed: **1 updated code elements**

2020-09-09 11:36 UTC, pxpm requested changes
Apart from my comment I very much welcome this PR. Thank you @mahasadhu 

This must have slipped while we refactored Filters into classes. So sorry for the trouble. 

If you don't have time to make the suggested changes let us know so we can finish this up and merge the PR. 

Wish you the best,
Pedro

2020-09-09 11:36 UTC, pxpm commented on src/app/Library/CrudPanel/CrudFilter.php
> +        $this->values = is_callable($value) ? $value() : $value;
We had trouble using this kind of check in the past, who knows what values could endup there :smiley: 

 Just to make sure we don't get into the same hole I would go here with: 

`$this->values = (!is_string($value) && is_callable($value)) ? $value() : $value;`

If the string is a php core function we know what is going to happen :+1:

2020-09-10 00:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/eccb5df4-1991-49d3-930d-a0b3678e7b48) was created.

2020-09-10 00:57 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/ba4bc982-04ad-4995-8188-8c67ea61d816) was created.

2020-09-10 01:04 UTC, mahasadhu commented
@pxpm Hi Pedro, thanks for checking 😃 

Sorry I did not know that. I've pushed some updates to the code.

Another idea, we can just close this PR and update the docs from this:
https://backpackforlaravel.com/docs/4.1/crud-fluent-syntax
![image](https://user-images.githubusercontent.com/13914485/92669476-3f16b580-f344-11ea-833b-b3c869b2be40.png)

to, for example, this:
```
            CRUD::filter('department')
                ->type('select2')
                ->label(trans('backpack::base.job_category'))
                ->values(\App\Models\Department::all()->pluck('name', 'id')->toArray())
                ->whenActive(function($value) { // if the filter is active
                    $this->crud->query->whereHas('project.department', function ($query) use ($value) {
                        $query->where('id', $value);
                    });
                });
```

Because (CMIIW) it seems no one has realized this errors yet. But it's up to you though, just a thought.

Thank you!

2020-09-10 01:12 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/eccb5df4-1991-49d3-930d-a0b3678e7b48) completed: **2 new issues**

2020-09-10 01:31 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/ba4bc982-04ad-4995-8188-8c67ea61d816) completed: **No new issues**

2020-09-10 10:54 UTC, pxpm commented
Hello @mahasadhu thank you very much once again :+1:

The refactor to use Fluent api for Filters happened not so long time, so that's why I think not so many people switch from old array definition to the new fluent syntax. 

The array definition supports anonymous functions in value key, this was just a mistake we let slip when refactoring to the Fluent API. 

With your PR merged the documentation should be ok ? 

Best,
Pedro

2020-09-10 13:55 UTC, mahasadhu commented
No problem at all @pxpm

Ah I see...
Yes it should be ok, no need to update the docs :smiley

Thank you

2020-09-15 13:19 UTC, tabacitu commented
Thank a lot @mahasadhu & @pxpm . You're right, of course. 
Merged, will be tagged later today, and be available as a patch update with `composer update`.

Keep 'em coming! Cheers.

2020-09-15 13:19 UTC, merged