Remove init buttons
Laravel-Backpack/CRUD pull request #3246
Opened 2020-10-06 08:34 UTC by pxpm

refs: #3244

2020-10-06 08:35 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/e24f41b0-bbba-40a8-b167-00cf8f5b1d91) was created.

2020-10-06 08:58 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/e24f41b0-bbba-40a8-b167-00cf8f5b1d91) completed: **No new issues**

2020-10-06 15:02 UTC, tabacitu requested changes
I think you also included some other changes about the `select_from_array` field, by mistake. Right?

One day @pxpm , I will convince you to try to use https://git-fork.com . 
I was blind but now I see. I no longer use the command line for Git.
One day you will see the light too!!! 🤣

2020-10-07 09:14 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/ab8eebc1-21a4-40ba-8cb8-b0dc79e4b9d6) was created.

2020-10-07 09:40 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/ab8eebc1-21a4-40ba-8cb8-b0dc79e4b9d6) completed: **No new issues**

2020-10-07 11:21 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/21991403-a178-449c-bdff-228d92630882) was created.

2020-10-07 11:22 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/638014bf-b0a9-4f8e-9912-7fc60b061496) was created.

2020-10-07 11:23 UTC, pxpm commented
@tabacitu It's open .. I just need to get used to it a little bit more hehe, thanks for the tip \o

Removed the unwanted code and added the tests for the `setRouteName()`

Best,
Pedro

2020-10-07 11:45 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/638014bf-b0a9-4f8e-9912-7fc60b061496) completed: **1 new issues, 2 updated code elements**

2020-10-14 13:11 UTC, tabacitu approved these changes
Excellent PR! Reviewed, tested, everything's AOK now.

2020-10-14 13:11 UTC, merged