change placeholder service
Laravel-Backpack/CRUD pull request #3425
Opened 2020-12-29 10:59 UTC by pxpm

refs: #3423 

It's not the first time it happens. `placehold.it` is now `placeholder.com`. Still it's not the first time they let the certificates expire. 

It's certificate is expired since 25th of december this year (even the new service `placeholder.com`

I am switching here for a new placeholder service, but still, I think we might want to have our own image creation process (maybe just css will be enough ? ) and don't rely on external services for something I am pretty sure lots of people leave by default.

Best,
Pedro

2020-12-29 10:59 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/88fd4b6f-2166-49e1-bb3d-4a2b77b31a94) was created.

2020-12-29 11:14 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/88fd4b6f-2166-49e1-bb3d-4a2b77b31a94) completed: **No new issues**

2021-01-04 12:43 UTC, tabacitu requested changes
Reviewed this, we could merge if we trust `place-hold.it` more than `placehold.it` but:
- I agree with you @pxpm that we should probably find a home-grown solution; maybe a simple CSS solution in Backpack 4.2?
- Right now... the normal `placehold.it` seems to be working for me again... so I don't know if it's worth changing... Is it now working for you guys too?

2021-01-04 12:43 UTC, tabacitu commented on src/helpers.php
> +                    return Gravatar::fallback('https://place-hold.it/160x160/00a65a/ffffff/&bold&fontsize=18&text='.$firstLetter)->get($user->email);
```suggestion
                    return Gravatar::fallback($placeholder)->get($user->email);
```

Looks like we hardcoded the URL two times. Over here we should already have this as `$placeholder` right?

2021-01-04 12:43 UTC, tabacitu commented on src/helpers.php
> +        $placeholder = 'https://place-hold.it/160x160/00a65a/ffffff/&bold&fontsize=18&text='.$firstLetter;
```suggestion
        $placeholder = 'https://place-hold.it/160x160/00a65a/ffffff/&fontsize=40&text='.$firstLetter;
```

I found no bold and font size 40 to be the closest to what we had before:
![2021-01-04 08 39 33](https://user-images.githubusercontent.com/1032474/103536169-669c0b80-4e68-11eb-8e5d-034e79c40ee8.gif)

2021-01-04 13:20 UTC, pxpm commented
Yes, it's working again @tabacitu 

Let this sit as a refactor in 4.2 I think. A lot of people for sure have this "avatar" by default. It's simple, work great and come with backpack by default. I think we can achieve the same with a css solution.

2021-01-04 13:22 UTC, tabacitu commented
Deal. 

Having the PR is a good thing anyway - if we have problems again we can just merge it before 4.2 👍

2021-01-04 13:23 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/b91bab05-99fc-43a7-be28-bcdc65b54d39) was created.

2021-01-04 13:45 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/b91bab05-99fc-43a7-be28-bcdc65b54d39) completed: **No new issues**

2021-04-03 10:41 UTC, pxpm commented
Just for reference, I achieved a "similar" looking with:

```html
<span class="backpack-avatar-menu-container">
            <span class="backpack-avatar-menu-text">
              {{backpack_user()->getAttribute('name') ? mb_substr(backpack_user()->name, 0, 1, 'UTF-8') : 'A'}}
            </span>
        </span>
```

```css
  .backpack-avatar-menu-container {
            padding-top: 0.5em;
            height: 35px;
            width: 35px;
            background-color: #00a65a;
            border-radius: 50%;
            display: inline-block;
  }
  .backpack-avatar-menu-text {
    font-size: 14px;
    color: white;
  }
```

2021-04-08 07:41 UTC, tabacitu commented
I like that! CSS here to save us! One thing I don't like about it is that it's not an image. So it's not non-breaking, since before we had:
```php
    <img class="img-avatar" src="{{ backpack_avatar_url(backpack_auth()->user()) }}" alt="{{ backpack_auth()->user()->name }}">
```

and now it'll have to be either an IMG or a SPAN. But it's the _optimal_ solution indeed for 4.2.

---

One other solution to bring this avatar inhouse, this time in a non-breaking way, would be to just... 
- create 26 images, one with each first letter of the alphabet. Like... copy-paste the ones generated by placehold right now, and bring them inhouse
- then we'd have an `user_avatar_placeholders` folder with `a.jpg`, `b.jpg` etc. 
- then inside the `backpack_avatar_url()` helper we could replace `placehold.it` with either 
    - the published image, if the `user_avatar_placeholders` directory exists (but in most cases it won't be published so it won't exist);
    - an URL that _we_ control, so `'https://backpackforlaravel.com/user_avatar_placeholders/'.$firstLetter.'.jpg'` instead of `'https://placehold.it/160x160/00a65a/ffffff/&text='.$firstLetter`

That way, no more calls to `placehold.it`. Best case, we use a local image. Worst case, we make a call to the backpack website, which we know will be up because it's in our control.  

🤷‍♂️ just sayin'

2021-04-08 13:52 UTC, pxpm commented
I would not go with an url we control. Domain issues, server issue, certificate issues, internet issues ... 

I think for a few months we could increase the package size by a little and use the local image solution. I also think that CSS is the real solution for this problem in 4.2.

ping @promatik what do you think ?

2021-04-25 15:24 UTC, promatik commented
I'm with @pxpm!
Placing the images on `backpackforlaravel.com` side is a permanent source of possible issues we are adding.
And the 26 images, if properly optimized, will be less than 10kb 🤷‍♂️

---

But, what if we use both solutions?
Image over the CSS solution, and on 4.2 we may deprecate the image.

2021-04-25 16:10 UTC, promatik commented
I made a proof of concept here: https://github.com/Laravel-Backpack/CRUD/pull/3681
I think it's a non breaking change, so it's a permanent solution for v4.1.

Let me know what you guys thing ✌

2021-09-06 07:43 UTC, tabacitu commented
Ok soo... you were right, I was wrong. CSS over third-party 🎉 Definitely. Thanks for keeping me in check guys! 

Instead of _changing vendors_, I think it's better for us to _remove vendors_ entirely. Since #3681 has been merged into 4.1,  let's do https://github.com/Laravel-Backpack/ideas/issues/114 instead of merging this PR please. 

Cheers!

2021-09-06 07:43 UTC, closed without merging