add configurable search operator for ListOperation
Laravel-Backpack/CRUD pull request #4314
Opened 2022-04-06 11:11 UTC by pxpm

## WHY

### BEFORE - What was wrong? What was happening before this PR?

This is an old issue since #1980 . There were workarounds, but we can make developers life easier. A few days a solution to solve this problem pop-up in #4277 but we talked about it and decided that it was better to make it configurable than "hardcode" ilike for some db's and like for others. 

### AFTER - What is happening after this PR?

We still use `like` by default, but the search operator is now configurable, so you can change it globally for ALL CRUDS in the `backpack.operations.list` config file, or per crud `$this->crud->setOperationSetting('searchOperator', 'ilike')` in your `setupListOperation`. 

## HOW

### How did you achieve that, in technical terms?

Added a config for the operator.

### Is it a breaking change?

No it's not.

2022-04-11 15:01 UTC, tabacitu requested changes
I love it. But let's make it `$searchOperator` not `$seachOperator` 😅

2022-04-11 15:05 UTC, pxpm commented on src/app/Library/CrudPanel/Traits/Search.php
> +            $seachOperator = config('backpack.operations.list.searchOperator', 'like');
```suggestion
            $searchOperator = config('backpack.operations.list.searchOperator', 'like');
```

2022-04-11 15:05 UTC, pxpm commented on src/app/Library/CrudPanel/Traits/Search.php
> +                    $query->orWhere($this->getColumnWithTableNamePrefixed($query, $column['name']), $seachOperator, '%'.$searchTerm.'%');
```suggestion
                    $query->orWhere($this->getColumnWithTableNamePrefixed($query, $column['name']), $searchOperator, '%'.$searchTerm.'%');
```

2022-04-11 15:05 UTC, pxpm commented on src/app/Library/CrudPanel/Traits/Search.php
> +                    $query->orWhereHas($column['entity'], function ($q) use ($column, $searchTerm, $seachOperator) {
```suggestion
                    $query->orWhereHas($column['entity'], function ($q) use ($column, $searchTerm, $searchOperator) {
```

2022-04-11 15:05 UTC, pxpm commented on src/app/Library/CrudPanel/Traits/Search.php
> +                        $q->where($this->getColumnWithTableNamePrefixed($q, $column['attribute']), $seachOperator, '%'.$searchTerm.'%');
```suggestion
                        $q->where($this->getColumnWithTableNamePrefixed($q, $column['attribute']), $searchOperator, '%'.$searchTerm.'%');
```

2022-04-14 05:43 UTC, tabacitu commented
This. Is. PERFECT!

![gutearbeitoriginals-perfect-top-l3q2LH45XElELRzRm](https://user-images.githubusercontent.com/1032474/163321273-0c95cd42-4e93-4803-ae5f-d5282e76711c.gif)

Non-breaking. Good naming. Surgical change. 
Thank you @pxpm ! Well done!

2022-04-14 05:43 UTC, merged

2022-05-04 12:58 UTC, siddharth-bhansali commented
I am guessing the relevant change is also needed on the FetchOperation trait to allow for case insensitive search in a select field with an ajax data source.

2022-05-05 13:23 UTC, pxpm commented
Hello @siddharth-bhansali and I guess you are right 🙃 

I've submitted the PR to pro that would:

- Make the searchOperator for Fetch by default the same that is defined for List. 
- Added it as a operation configuration, so you can change it if it's different from the List one. 

Thanks for the feedback 🙏

2022-05-05 13:23 UTC, pxpm commented
Hello @siddharth-bhansali and I guess you are right 🙃 

I've submitted the PR to pro that would:

- Make the searchOperator for Fetch by default the same that is defined for List. 
- Added it as a operation configuration, so you can change it if it's different from the List one. 

Thanks for the feedback 🙏

2022-05-05 19:07 UTC, siddharth-bhansali commented
@pxpm great! I had been following this thread for a while now and eagerly was waiting for the change, however didn't happen with the select. For now I have overridden the trait, but a configurable operator would be great! Thank you very much!