support repeatable fields in js api
Laravel-Backpack/CRUD pull request #4376
Opened 2022-05-15 16:48 UTC by pxpm

this adds support to work with repeatable fields using the same js api. 

added the `repeatable(fieldName, repeatableName, rowNumber)` helper so developer can target fields inside the repeatable in specific rows. 

```php
crud.repeatable('field_1', 'repeatable').change(function(e, value, rowNumber) {
    if(value.length > 0) {
        crud.repeatable('field_2', 'repeatable', rowNumber).hide(); 
    }
});
```

2022-05-16 15:43 UTC, tabacitu requested changes
Let's rename `repeatable()` to `subfield()` please 🙏

```php
// we have
crud.field();

// so we should also have
crud.subfield('name', 'testimonials').change(function(e, value, rowNumber) {
    if(value.length > 0) {
        crud.subfield('position', 'testimonials', rowNumber).hide(); 
    }
});
```

2022-05-23 07:11 UTC, pxpm commented
@tabacitu I've renamed repeatable into subfield, but now we have an inconsistency with `checklist_dependency` that has subfields but are not for `repeatable containers`. In `checklist_dependency` we should keep using `crud.field()` and not `crud.subfield()` as the `checklist_dependency` subfields are not going inside a repeatable container.

2022-05-23 08:58 UTC, tabacitu commented
Got it! Can you please check and fix the merge conflicts, please 🙏

2022-05-23 17:00 UTC, tabacitu reviewed
Good job here @pxpm ! This looks like quite a bit of work! I didn't expect adding support for `repeatable` to be this few lines... Though I can tell they've been written with sweat and tears 😅

There's something here that triggers my spidey-sense... but I can't put my finger on it... Let's figure it out together, please.

Overall, I feel this pollutes the existing CrudField a bit, that we're kind of bending and twisting CrudField in order to also cover subfields... So let's think... what can we do about that... How can we separate this new bit of logic, needed for repeatable?

@promatik we could use your 2 cents here too - you know (and like) JS better than we do.

2022-05-29 10:44 UTC, pxpm commented
Closing in favor of #4403

2022-05-29 10:44 UTC, closed without merging