add update command
Laravel-Backpack/CRUD pull request #4782
Opened 2022-11-21 04:14 UTC by tabacitu

## WHY

### BEFORE - What was wrong? What was happening before this PR?

In order to publish the CSS and JS assets you had to google how to do it, in order to copy-paste this:

```bash
php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=”public” --force
```

### AFTER - What is happening after this PR?

You can do the above using:

```bash
php artisan backpack:update
```

## HOW

### How did you achieve that, in technical terms?

Added a new command.

### Is it a breaking change?

No. But the command name is pretty general.

### How can we test the before & after?

Do `php artisan backpack:update` and it should do the same thing as the other command (publish CRUD assets).

2022-11-21 04:14 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/7bc69546-f179-48d3-88c1-638cd321948c) was created.

2022-11-21 04:40 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/7bc69546-f179-48d3-88c1-638cd321948c) completed: **3 new issues, 3 updated code elements**

2022-11-28 13:50 UTC, pxpm requested changes
@tabacitu totally agree with the purpose, but 100% against the name. 

`php artisan backpack:assets-publish`
`php artisan backpack:publish-assets`
`php artisan backpack:public-assets`

Any of those are better of `Update` I guess.

2022-11-28 18:15 UTC, tabacitu commented
Haha fair enough @pxpm . That's the reason I didn't hit `merge`, I wasn't quite comfortable with `php artisan backapck:update` either.

Ok let's go with `php artisan backpack:publish-assets` then. Will do!

2022-11-30 07:50 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/83451f78-0e3b-42b9-8df3-11507a4cf7fe) was created.

2022-11-30 07:51 UTC, tabacitu commented
I renamed it to `php artisan backpack:publish-assets`. Could you please double-check / polish / merge, Pedro?

2022-11-30 08:32 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/83451f78-0e3b-42b9-8df3-11507a4cf7fe) completed: **3 new issues, 3 updated code elements**

2022-11-30 15:26 UTC, pxpm commented on src/app/Console/Commands/PublishAssets.php
> +            }
```suggestion
            $this->line($buffer);     
```

2022-11-30 15:29 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/3e8f7ecc-8c5c-4ee2-bad6-0523c454116d) was created.

2022-11-30 15:30 UTC, merged