AuthenticatesSessions contract doesn't exist in L8
Laravel-Backpack/CRUD pull request #4849
Opened 2022-12-17 12:10 UTC by pxpm

## WHY

### BEFORE - What was wrong? What was happening before this PR?

When we updated our session middleware we updated it to the latest Laravel version that has a contract (interface) that's not available in L8. 

That broke our installations on L8, as reported in https://github.com/Laravel-Backpack/CRUD/issues/4848

### AFTER - What is happening after this PR?

We conditionally load the class with or without the interface depending on Laravel version. It's ugly, but it works 😞 

## HOW

### How did you achieve that, in technical terms?

Conditionally load the middlware with or without the interface.

### Is it a breaking change?

No, I don't think so.

### How can we test the before & after?

Try to install L8 with Backpack.

2022-12-17 12:10 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/9eda13b6-b57f-4687-8356-b87ba6ee45d6) was created.

2022-12-17 12:30 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/9eda13b6-b57f-4687-8356-b87ba6ee45d6) completed: **6 updated code elements**

2022-12-18 11:39 UTC, tabacitu requested changes
Ouch! It's indeed ugly but... I guess it's the only way we can do this... in a non-breaking way... yes... good thinking @pxpm . I really don't have another solution, so good find!

I gave the PR a quick look and... I have two worries:

(1) Are you sure this is doing what we want, in both scenarios (L8 and L9)? The way I read this PR:
- the code that was working for L9 was moved in an `AuthenticateSessionsL8` class;
- for L9 now we're no longer doing anything, we're just loading Laravel's default;

While that probably doesn't trigger the error any more, I think we lose all that we were trying to do in this middleware, on L9. Please double-check or explain why I'm wrong.

(2) At the risk of duplication, let's refactor this so it's a little clear what's happening. Assuming I'm right on the point above, that means this class needs some methods for both L9 and L8. So in that case, let's use this file as a switchboard, something like:

```php
if (class_exists(BlaBla::class)) {
    include(L9);
} else {
    include (L8);
}
```

And if `include()` is too ugly to do here... even placing both of them in one file... is ok with me. It'll be ugly no matter how we do it.

That should make it easier to determine the differences between L8 and L9 behaviour.

What do you think, Pedro?

2022-12-19 12:25 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/0b9f3b54-1d03-42f2-9e41-4122cd716aea) was created.

2022-12-19 12:26 UTC, pxpm commented
Thanks for the review @tabacitu .

Your assertion is not totally correct. 

We include the same file we had before https://github.com/Laravel-Backpack/CRUD/blob/main/src/app/Http/Middleware/AuthenticateSession.php the only difference is that we broke it when implementing the interface (L9). 

For that reason, I created a file that does not implement the interface to be used in L8, and we use the same file, but implementing the interface. 

In the end, this file didn't exist in L8, so it shouldn't need nothing at all from this middleware when using L8. 

I've refactored accordingly. The file `AuthenticatesSessionsL9` is only included when the Interface is present. No file for L8.

2022-12-19 13:04 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/0b9f3b54-1d03-42f2-9e41-4122cd716aea) completed: **6 updated code elements**

2022-12-19 16:37 UTC, merged