[Feature] Add option to display actions column as dropdown
Laravel-Backpack/CRUD pull request #4999
Opened 2023-03-27 07:48 UTC by maurohmartinez

## WHY

### BEFORE - What was wrong? What was happening before this PR?

Nothing! [Here](https://github.com/Laravel-Backpack/CRUD/issues/4963) it is well explained.

### AFTER - What is happening after this PR?

Basically... this!

![actions-column-as-dropdown-button](https://user-images.githubusercontent.com/33960976/227874064-b353f995-3935-4883-9f52-ae9b17896835.gif)

## HOW

### How did you achieve that, in technical terms?

Most changes are done in js, `src/resources/views/crud/inc/datatables_logic.blade.php`. A new operation setting is added in order to control it `actionsColumnAsDropdown`, since there might be people nostalgic about the old ways... :)

```
$this->crud->displayActionsColumnAsDropdown(false);
```

### Is it a breaking change?

Nope.

### How can we test the before & after?

Checkout this branch and test if columns can now be displayed as dropdown. Also, `$this->crud->displayActionsColumnAsDropdown(false);` should revert it to the old line stack.

2023-03-27 07:48 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/344fd43c-53a5-46a7-9a8e-46de23fd9a81) was created.

2023-03-27 08:29 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/0ee0abf3-5b3c-442b-8dc9-98934a36e6c3) completed: **1 updated code elements**

2023-03-27 09:14 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/df850bc8-0099-43de-bd38-33e841b409ca) was created.

2023-03-27 09:44 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/df850bc8-0099-43de-bd38-33e841b409ca) completed: **1 updated code elements**

2023-03-27 14:00 UTC, tabacitu commented
I love this! ❤️ This is a GREAT solution Mauro - can't belive how simple it is using JS. 

The naming is good too. I took another look, it makes sense it like this because it's similar to other configs we have.

The only thing I'd change is the default. Let's default to `false`. If that's done, and you've tested this on all themes, I'll happily test and merge this to v6 🎉

2023-03-27 14:00 UTC, tabacitu requested changes

2023-03-27 14:00 UTC, tabacitu commented on src/config/backpack/operations/list.php
> +    'actionsColumnAsDropdown' => true,
```suggestion
    'actionsColumnAsDropdown' => false,
```

2023-03-29 07:13 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/eff7a9cc-e9c2-41bf-8b2e-cbc8f82b86c9) was created.

2023-03-29 07:27 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/17f369ce-35b1-4a01-aa3a-3de4fd278fa0) was created.

2023-03-29 08:23 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/983b7d42-2414-47b4-93f7-1b434e9daf85) was created.

2023-03-29 08:26 UTC, maurohmartinez commented
@tabacitu tested it with other templates, and it looks good!

I made one small change to common.css (not related to this), but also tested that in other themes and it works good.

2023-03-29 08:32 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/832640ba-c875-4ff8-bdc7-50485f426d38) was created.

2023-03-29 08:42 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Laravel-Backpack/CRUD/inspections/955d7db5-b842-4473-b14c-2a64c630f448) was created.

2023-03-30 10:34 UTC, maurohmartinez commented
Close in favor of https://github.com/Laravel-Backpack/CRUD/pull/5005

2023-03-30 10:34 UTC, closed without merging