[v6] Allow arrays in CrudField constructor.
Laravel-Backpack/CRUD pull request #5080
Opened 2023-05-23 14:43 UTC by pxpm

## WHY

### BEFORE - What was wrong? What was happening before this PR?

It was not possible to construct the `CrudField` with an array because some fields like `date_range` and `checklist_dependency` used arrays as their names. 

### AFTER - What is happening after this PR?

We can construct the `CrudField` with an array like with `CRUD::addField([...])`. The main difference is that `addField` return the `CrudPanel` object, while `field([...])` will return the `CrudField` object, so that you can continue to fluently define the field. 

**IMPORTANT**: This is not ready to merge, this is waiting for other PR's to get merged first.

2023-05-25 11:44 UTC, tabacitu requested changes

2023-05-25 11:44 UTC, tabacitu commented on src/app/Library/CrudPanel/CrudField.php
> +    public function __construct($nameOrDefinition)
Let's call this `$nameOrDefinitionArray` so it's clearer.

2023-05-25 11:59 UTC, pxpm commented on src/app/Library/CrudPanel/Traits/Fields.php
> +            $fieldsArray[$field['name']][$attributeName] = $attributeValue;
We just used the field key to transform the arrayed field names into `valid_string`. 

If the name is always a valid string now we can use it as the key. 

Most of the time (when the field name was not an array) the key was already the `$field['name']`.

2023-05-26 08:37 UTC, tabacitu commented on src/app/Library/CrudPanel/Traits/Fields.php
> +            $fieldsArray[$field['name']][$attributeName] = $attributeValue;
Aaah excellent! I love it when we shoot two birds with one stone! 🪨 → 🕊️🕊️

2023-05-26 13:40 UTC, tabacitu commented
I like how this looks now! Well done!

But are you sure it's working? In our v6 demo as soon as I go to Users or Monsters (entities that have `date_range` or `checklist_dependency` I get a big fat error: https://flareapp.io/share/v5pZRlxP#F47

<img width="1512" alt="CleanShot 2023-05-26 at 16 39 21@2x" src="https://github.com/Laravel-Backpack/CRUD/assets/1032474/cc5edfe2-fbf2-47a8-9223-ed568c8150a5">

2023-05-26 15:10 UTC, tabacitu commented
Tested, working now! 🎉

2023-05-26 15:11 UTC, merged