fix: deprecation on dynamic property (PHP82)
Laravel-Backpack/CRUD pull request #5082
Opened 2023-05-25 06:29 UTC by thomascombe

## WHY

I have a lot a warning on Backpack login:
```
[2023-05-24 17:15:46] production.WARNING: ErrorException: Creation of dynamic property Backpack\CRUD\app\Http\Controllers\Auth\LoginController::$redirectAfterLogout is deprecated in /laravel/vendor/backpack/crud/src/app/Http/Controllers/Auth/LoginController.php:51
```

On **PHP 8.2** env.

## HOW

I replace dynamic properties with nullable (and default null) properties.

### Is it a breaking change?

No breaking change.

### How can we test the before & after?

1. Try a login / forget / reset password
2. Try to override `$redirectTo` on LoginController ([doc](https://backpackforlaravel.com/docs/5.x/base-how-to#customizing-the-auth-controllers))

2023-10-18 09:43 UTC, pxpm requested changes
Hey @thomascombe thanks for the PR. really appreciated🙏 

I've left some review comments. Please let me know if you don't agree with something I've proposed. 

If you have time/desire to take this PR to the end, we can do this 🥳  . 
If not, no worries at all, I can just pick it up and finish it. 

Cheers

2023-10-18 09:43 UTC, pxpm commented on src/app/Http/Controllers/Auth/LoginController.php
> +        $this->loginPath = ! empty($this->loginPath) ? $this->loginPath : backpack_url('login');
```suggestion
        $this->loginPath ??= backpack_url('login');
```

2023-10-18 09:43 UTC, pxpm commented on src/app/Http/Controllers/Auth/LoginController.php
> +        $this->redirectTo = ! empty($this->redirectTo) ? $this->redirectTo : backpack_url('dashboard');
```suggestion
        $this->redirectTo ??= backpack_url('dashboard');
```

2023-10-18 09:43 UTC, pxpm commented on src/app/Http/Controllers/Auth/LoginController.php
> +        $this->redirectAfterLogout = ! empty($this->redirectAfterLogout) ? $this->redirectAfterLogout : backpack_url('login');
```suggestion
        $this->redirectAfterLogout ??= backpack_url('login');
```

2023-10-18 09:43 UTC, pxpm commented on src/app/Http/Controllers/Auth/RegisterController.php
> +        $this->redirectTo = ! empty($this->redirectTo) ? $this->redirectTo : config('backpack.base.route_prefix', 'dashboard');
```suggestion
        $this->redirectTo ??= config('backpack.base.route_prefix', 'dashboard');
```

2023-10-18 09:43 UTC, pxpm commented on src/app/Http/Controllers/Auth/ResetPasswordController.php
> +    private string $redirectTo;
```suggestion
    protected ?string $redirectTo = null;
```

2023-10-18 09:43 UTC, pxpm commented on src/app/Http/Controllers/Auth/ResetPasswordController.php
> +        $this->redirectTo = ! empty($this->redirectTo) ? $this->redirectTo : backpack_url('dashboard');
```suggestion
        $this->redirectTo ??= backpack_url('dashboard');
```

2023-10-20 09:58 UTC, thomascombe commented
Hey @pxpm, thanks for review.

Good point for null coalesce feature. 
I haven't used it to keep old PHP compatibility, but Laravel 10 is PHP 8.1 and higher compatible, so : let's go 👍 

All suggestions are apply ✅

2023-10-20 14:26 UTC, pxpm commented
Thanks @thomascombe 🙏 Much appreciated!

2023-10-20 14:26 UTC, merged