Create method locale override
Laravel-Backpack/CRUD pull request #5448
Opened 2024-02-16 13:58 UTC by PedroTeixeira-unP

## WHY

### BEFORE - What was wrong? What was happening before this PR?

On crud creation it wouldn't set the translations to all the available languages, leaving blank spaces

### AFTER - What is happening after this PR?

This PR gives the option assign the current field not only into the current user lang but all the available

## HOW

### How did you achieve that, in technical terms?

A config field to disable/enable this option.
If true it fetches all the available languages and it loops by them

### Is it a breaking change?

No, in case the config key doesn't exists the code will keep the current/old method running

### How can we test the before & after?

Create a new entry where there's a translatable field
Change the config key between true/false

2024-02-16 15:46 UTC, pxpm requested changes
Hey @PedroTeixeira-unP thanks for the PR, really appreciated. 

I am trying to understand if this is a good thing to do, at the moment I don't think this should be done. 
I have two main reasons that believe are show stoppers, unless I am wrong:
- **1)** We will have "misleading" information in the database. The `title.fr => 'Olá tudo bem'` is not very accurate is it ? 
- **2)** You lose the ability to know what languages are translated and what are missing, because everything will be "translated" by default.

Having this behind a configuration does not worry me, I know it will be safe. 
But I am not seeing the use case where having all keys with the same translation on the database would be a nice thing to have. 

I think I may get the reason why you want to do this, correct me if I am wrong, but the intention is to when you edit the entry in other locales you have the "native translation" there ? 

If that's the case I agree with you, it's a pain point at the moment. We already have some PR's and discussions open to address that:
- https://github.com/Laravel-Backpack/CRUD/pull/4267
- https://github.com/Laravel-Backpack/CRUD/pull/4271

Is that something that would work for you ? 

Let me know more, so that we merge/close this and/or prioritize those PR's I mentioned. 

Cheers

2024-02-16 15:46 UTC, pxpm commented on src/config/backpack/crud.php
> +    'override_available_locales_on_create' => true,
This can't be true by default or it would be a BC. 
```suggestion
    'override_available_locales_on_create' => false,
```

2024-02-16 15:46 UTC, pxpm commented on src/app/Models/Traits/SpatieTranslatable/HasTranslations.php
> +                if (config('backpack.crud.override_available_locales_on_create')) {
I don't think the config name represents what we would like to do here. 
We are "overwriting" anything, as there is nothing in other locales at the moment. 

So something like `backpack.crud.fill_missing_locales` would be more descriptive/accurate I think.

2024-02-16 16:17 UTC, PedroTeixeira-unP commented
Hi @pxpm, thank you for the reply

I believe there's a valuable use for this feature. 

While allowing autofill for other languages may sometimes result in inaccuracies in the translations, in certain scenarios, leaving these fields empty is not ideal. 

Having the ability to fill the translations might be a beneficial option, in my opinion.

I will also check those PR's  👌

2024-02-16 16:30 UTC, pxpm commented
> While allowing autofill for other languages may sometimes result in inaccuracies in the translations, in certain scenarios, leaving these fields empty is not ideal.

This are the scenarios I want to know more about, can you elaborate please ? 

Is it necessary to set the text on the other translation keys, or just init the translation keys ? I mean:
```diff
- [{pt: "ola", en: "ola", fr: "ola"}]
+ [{pt: "ola", en: "", fr: ""}]
```
I believe at the moment we only store ` [{pt: "ola"}]` right ? 

Let me know more about it.

Cheers
`

2024-06-04 05:44 UTC, tabacitu commented
Hey guys,

I also don't think this is a good idea, so I'm going to close the PR. Storing `title.fr => 'Olá tudo bem'` in the database should NOT be supported, because it breaks database integrity. The database no longer has correct information, it has false information.

For use cases where this is a good idea, I think the developer should implement workarounds on the PRESENTATION side, NOT the database side. For example, they can do something like `$product->title['en'] ?? $product->title['fr'] ?? $product->title['fr']`. Personally, I would create a method in the Model that would return ANY translation, something like `$product->any('title')`. That would fix my use case on the presentation side, and still have the DB information correct. If I want to understand what has been translated and what not... I can still do that.

Hope the explanation helps.
Cheers!

2024-06-04 05:44 UTC, closed without merging