[POC] datatable as a component for multiple cruds
Laravel-Backpack/CRUD pull request #5688
Opened 2024-10-11 12:59 UTC by pxpm

This is a very early POC about something me and @tabacitu are exploring. 

What we are trying to achieve here, can be summed up in the following way: 
- re-usable Datatable
- multiple CrudPanel instances in the same request. 

They way Backpack was built from start, although simple, comes with some limitations. Now that we want to introduce more advanced features we'd need to do major refactors of the software, that would take months for us to develop, and a lot of time for our users to upgrade. 

We are always exploring the possibility of changing something internal that would allow us to do more advanced things, without the cost for the developers that use our software. 

That said, one of the most requested features and needs we had, was to have a "relation table", without having to develop a new table from scratch, given how much effort we already spent on the Datatable/columns, and the **huge** amount of features we have on both of them. 

Without much to add for the moment, we will need to decide on the direction we would like to take, here is a screenshot of somewhat we want to achieve: 

![image](https://github.com/user-attachments/assets/108822fb-c0ac-4ac1-96f8-84732a9b9c22)

All of that, with the simplicity we aim for our software: 
```php
// in MonsterCrudController.php
$this->crud->addColumn([
            'name'        => 'crudColumn',
            'type'        => 'crud_column',
            'controller'  => IconCrudController::class,
        ]);

// in IconCrudController.php
protected function setupListOperation()
    {
        $this->crud->addColumns(['name', 'icon']);
        $this->crud->addFilter([
            'type'  => 'text',
            'name'  => 'name',
            'label' => 'Name',
        ]);
    }
```

At the moment there are 0 breaking changes, but also stuff that does no properly work. This is **very very** wip, we may find something that would require a major breaking change that we are not willing to do for the next version .. but it's a start. 👍

2025-03-26 15:34 UTC, tabacitu requested changes
Let's
1. Polish with the comments here.
2. Set up a demo 
- [ ] used a column in ShowOperation
- [ ] used as a widget in ShowOperation
- [ ] used in a dashboard as an x-component

2025-03-26 15:34 UTC, tabacitu commented on src/resources/views/crud/datatable/datatables_logic.blade.php
> +@php
Ok let's do it. Let's clean up this file a bit - let's take it step-by-step. First: let's remove the PHP from this file.

2025-03-26 15:34 UTC, tabacitu commented on src/resources/views/crud/columns/crud_column.blade.php
```php
$this->crud->addColumn([
            'name'        => 'crudColumn',
            'type'        => 'crud_column',
            'controller'  => IconCrudController::class,
            // OPTIONAL:
            // 'afterSetup' => function($crud) {
                $crud->addClause();
            }
        ]);
```

2025-03-26 15:34 UTC, tabacitu commented on src/app/Library/Datatable/Datatable.php
> +<?php
Will also accept the Controller, so the initialization is done here

2025-03-26 15:34 UTC, tabacitu commented on src/app/Library/CrudPanel/CrudButton.php
> +    public function getHtml($entry = null, $crud = null)
Let's remove this second parameter

2025-03-26 15:34 UTC, tabacitu commented on src/BackpackManager.php
> +        $crud->setOperation('list');
🚩 why hard-coded for the list operatin? In the future, we should be able to use BackpackManager to load a Form component, right?

2025-03-26 15:34 UTC, tabacitu commented on src/BackpackManager.php
> +        $crud->setOperation('list');
Maybe....

```php
getOperationFromController(string $controller, string $operation)
```

Or maybe we move this line to a separate method?! 🤷‍♂️

2025-03-26 15:34 UTC, tabacitu commented on src/BackpackManager.php
> +    public function getControllerCrud(string $controller): CrudPanel
let's think more about the names 🤷‍♂️

2025-04-29 09:58 UTC, tabacitu commented on src/resources/views/crud/inc/filters_navbar.blade.php
>      if(typeof updateDatatablesOnFilterChange !== 'function') {
Todo: after the review, we should probably move this JS logic from the FILTERS blade file... to the DATATABLES blade file. Right? I mean... filters are a general-purpose feature... that is supported by whatever operation wants to support them.

DataTables - as a component and as an operation... chooses to support the filters. So the logic that says "_when filter does X datatables does Y_" should probably live in the DATATABLE, not in the FILTERS.

2025-04-29 09:58 UTC, tabacitu commented on src/resources/views/crud/inc/filters_navbar.blade.php
>      if(typeof updateDatatablesOnFilterChange !== 'function') {
But right now it's ok here, just to keep the diff minimal. We can create a different PR that moves code around. Like a cleanup PR.

2025-04-29 09:58 UTC, tabacitu commented on src/BackpackManager.php
> +final class BackpackManager
What does this manage in Backpack... only CRUD Panels, right? So then... perhaps we should call it `CrudPanelManager` instead?

Think about it this way... if we have 3 separate packages: `backpack/ui`, `backpack/auth` and `backpack/crud`... where would this live? Inside the CRUD package right? So then it's an over-reach to say it's a BackpackManager, it's actually a `CrudPanelManager`.

2025-04-29 09:58 UTC, tabacitu commented on src/Backpack.php
> +<?php
Help me understand... what will this facade facilitate - what kind of calls? I'm wondering whether we need a Facade at all... or whether we should change its name.

2025-04-29 09:58 UTC, tabacitu commented on src/Backpack.php
> +<?php
Is it to do stuff like `Backpack::getActiveController` and `Backpack::getCrud()`? If so... I think we're better of doing `CrudManager::getActiveController()` and `CrudManager::getCrud()`.

I wouldn't expand this feature so much as to identify it with the Backpack name. It would prevent us from using the Backpack class for anything else in the future.

2025-04-29 09:58 UTC, tabacitu commented on src/BackpackServiceProvider.php
> +        Blade::component('datatable', Datatable::class);
Why do we need to register the component manually? Do we not have a namespace/directory where they get registered automatically?

2025-04-29 09:58 UTC, tabacitu commented on src/app/Http/Controllers/CrudController.php
> +    private function triggerControllerHooks()
I think this is a bad name for this function. Sure, it triggers the controller hooks... but that's just the SMALL part of what it does. What it does MORE IMPORTANTLY is to... setup the crud controller? O what is it? Cause I see it's calling the general-purpose setup methods like `setupDefaults()` and `setup()` but it's also calling `setupConfigurationForCurrentOperation()` which is an operation-thing.

Perhaps we call this method:
```suggestion
    private function setupCrudController()
```

If you don't have a better name for it.

2025-04-29 09:58 UTC, tabacitu commented on src/app/Http/Controllers/CrudController.php
> +            $this->initialized = true;
Something's fishy here. I see that we have a function called `initializeCrud()` but we are also doing `$this->initialized=true` outside of it. That is fishy. How can we refactor this bit of code so it's cleaner?

2025-04-29 10:03 UTC, tabacitu commented on src/BackpackServiceProvider.php
> +        $this->app->bind('crud', function ($app) {
Though all of the code here seems like something that should live in the CrudPanelManager class right? Maybe as a static function... something like `CrudPanelManager::getActiveCrudPanelInstance()` or something like that?

2025-05-12 11:49 UTC, pxpm commented on src/app/Http/Controllers/Operations/ListOperation.php
> +        \Backpack\CRUD\app\Library\Datatable\Datatable::applyCachedConfig($this->crud);
So there is the need to store the datatable "configuration closure" for the parent crud because we cannot setup the parent columns on the "current crud". 
Scenario: MonsterCrud setup a datatable for ProductCrud. It sets up the "configure" closure. 
When the ProductCrud table makes the request to product crud, we cannot run the "setup list" again, to get the closure. So we store that closure when the panel first initializes, and re-use that cached config in the ajax request.

2025-05-20 05:30 UTC, tabacitu commented on src/resources/views/crud/datatable/datatables_logic.blade.php
> +@php
Postponed

2025-05-20 06:46 UTC, tabacitu requested changes
Found quite a few things:

2025-05-20 06:46 UTC, tabacitu commented on src/resources/views/crud/columns/datatable.blade.php
Is there any way for me to pass some custom classes to the widget, or its wrapper? I see this need already, to add some margin at the top/bottom of a component.

I expect to be able to be able to pass something like `class => 'my-2'` to avoid this:

![CleanShot 2025-05-20 at 09 04 15](https://github.com/user-attachments/assets/0cc8bba5-022b-4955-90ba-93bd9ca0e337)

2025-05-20 06:46 UTC, tabacitu commented on src/resources/views/crud/datatable/datatable.blade.php
I'm looking at an empty datatable widget and it looks broken:

![CleanShot 2025-05-20 at 09 07 05](https://github.com/user-attachments/assets/ca7fe41c-d7d5-409b-af2c-340be5f7f850)

2025-05-20 06:46 UTC, tabacitu commented on src/resources/assets/css/common.css
I have a feeling the changes in this file did NOT stick to only changing datatables... that it also changed other things, because now I notice quite a few things work, but look half-baked:

### Create/Update operation - weird border + weird bkg for tabs

![CleanShot 2025-05-20 at 09 10 27](https://github.com/user-attachments/assets/3ab54a14-8bac-4d52-ba5c-c94724216b32)

### Show operation - weird bkg and borders for tabs

![CleanShot 2025-05-20 at 09 11 29](https://github.com/user-attachments/assets/f58fdd90-c172-4056-b544-bd1aeaf10b2f)

2025-05-20 06:46 UTC, tabacitu commented on src/resources/views/crud/columns/datatable.blade.php
Regarding the datatable column... Here's what I did. I went to the OwnersCrudController, and wanted to add in its Show Operation a datatable with pets.

So I did this:

```php
    protected function setupShowOperation()
    {
        // $this->setupListOperation();

        $this->crud->column('pets')
                    ->type('datatable')
                    ->controller('App\Http\Controllers\Admin\PetShop\PetCrudController');
    }
```

Which from what I understand should work. But it doesn't... it throws this error:

![CleanShot 2025-05-20 at 09 24 29](https://github.com/user-attachments/assets/fd5806fe-8592-41dd-9e76-f756c8a5d8b2)

---

Please note that if I give this column the name `pets_table` it will work. But it does NOT work if I give it the name of the actual column in the DB... why?

2025-05-20 06:46 UTC, tabacitu commented on src/resources/views/crud/columns/datatable.blade.php
Then I wanted to only show the pets from this owner... and that didn't work either... because `$entry` is null... why would `$entry` be null  here - we are inside the ShowOperation...

```php
    protected function setupShowOperation()
    {
        $this->setupListOperation();

        CRUD::column('pets_table')
                ->type('datatable')
                ->controller('App\Http\Controllers\Admin\PetShop\PetCrudController')
                ->configure(function ($crud, $entry = null) {
                    // only show the pets of this owner (owner is an n-n relationship)
                    $crud->addClause('whereHas', 'owners', function ($query) use ($entry) {
                        $query->where('id', $entry->id);
                    });
                });
    }
```

2025-05-20 06:46 UTC, tabacitu commented on src/resources/views/crud/columns/datatable.blade.php
If we have the `datatable` widget in PRO, why not move the `datatable` column there too? It's a complex feature, that took a lot of time to develop... why give it away for free.

Because it's just one line of code so it's easy to copy? 😅 Ok good argument. But still... it makes sense as a PRO feature, right? Not sure - let me know.

2025-05-20 06:46 UTC, tabacitu commented on src/app/Library/Datatable/Datatable.php
> +        $this->tableId = 'crudTable_'.$uniqueId;
If all these lines are just to set the tableId, why not clean this up and create a function for it?

```suggestion
        $this->crud ??= CrudManager::crudFromController($controller);
        $this->tableId = $this->generateTableId();
```

2025-05-20 06:46 UTC, tabacitu commented on src/resources/views/crud/inc/filters_navbar.blade.php
Whoooaaah. I looked at [the PRO diff](https://github.com/Laravel-Backpack/PRO/compare/next...datatable-agnostic) and I saw this:

![CleanShot 2025-05-20 at 09 42 54@2x](https://github.com/user-attachments/assets/85547f1f-5f30-4ff3-833a-531385c69f2c)

This is a huge red flag. What's happening here?! We just made the filters agnostic... now we're adding info about the table in them?! Something's very VERY fishy here @pxpm

2025-05-20 12:36 UTC, tabacitu commented on src/resources/views/crud/columns/datatable.blade.php
Let's think about it - maybe we have two different methods 
- `configure($crud)`, which runs right after `setupListOperation()`
- `configureResults($crud, $entry)` which runs after the above, basically inside the AJAX request;

Maybe... I dunno.

2025-05-21 15:53 UTC, pxpm commented on src/resources/views/crud/columns/datatable.blade.php
As we talked, you can use the 'wrapper' property on the widget to add a bottom border. 
I've just added it into the demo

2025-05-26 14:05 UTC, tabacitu commented on src/app/Http/Controllers/Operations/ListOperation.php
> +        \Backpack\CRUD\app\Library\Datatable\Datatable::applyCachedConfig($this->crud);
```suggestion
        // If there's a config closure in the cache for this CRUD, run that configuration closure.
        // This is done in order to allow the developer to configure the datatable component.
        \Backpack\CRUD\app\Library\Datatable\Datatable::applyCachedConfigurationClosure($this->crud);
```

2025-05-26 14:06 UTC, tabacitu commented on src/app/Library/Datatable/Datatable.php
> +    public static function applyCachedConfig($crud)
```suggestion
    public static function applyCachedConfigurationClosure($crud)
```

2025-06-02 08:38 UTC, tabacitu commented on src/resources/views/crud/datatable/datatables_logic.blade.php
This PR broke editable_columns:

![CleanShot 2025-06-02 at 11 37 33@2x](https://github.com/user-attachments/assets/b047f889-dfe0-470e-a338-00631283197f)

2025-06-02 08:53 UTC, tabacitu reviewed
Checked - still need to talk about this and decide on naming.

2025-06-02 14:33 UTC, tabacitu commented on src/app/Library/Datatable/Datatable.php
> +    ) {
```suggestion
    public function __construct(
        private string $controller,
        private ?CrudPanel $crud = null,
        private bool $modifiesUrl = false,
        private ?\Closure $setup = null,
        private ?string $name = null
    ) {
```

Note here - we can remove the `type` parameter.

2025-06-02 14:43 UTC, tabacitu commented on src/resources/views/crud/datatable/datatable.blade.php
> +
The table count doesn't show when the component is used alone - it only shows in the main ListOperation view.

We need to move the table title and subtitle to the component.

2025-06-02 14:44 UTC, tabacitu commented on src/resources/views/crud/datatable/datatable.blade.php
> +
Different PR please.

2025-06-02 14:45 UTC, tabacitu commented on src/app/Library/Datatable/Datatable.php
> +    private function storeDatatableConfig()
```suggestion
    private function cacheDatatableConfig()
```

2025-06-02 14:46 UTC, tabacitu commented on src/app/Library/Datatable/Datatable.php
> +    public static function applyCachedConfigurationClosure($crud)
```suggestion
    public static function applyCachedSetupClosure($crud)
```

2025-06-02 15:00 UTC, tabacitu commented on src/app/Library/Datatable/Datatable.php
> +            $parentCrud = CrudManager::crudFromController($cachedData['parentController'], 'show');
This is hard-coded to only work inside the `show` and `list` operations. And it needs to work inside any operation (even custom ones).

2025-06-02 15:04 UTC, tabacitu commented on src/app/Library/Datatable/Datatable.php
> +                }
Removable

2025-06-02 15:07 UTC, tabacitu commented on src/CrudPanelManager.php
> +    private $requestController = null;
Maybe this isn't required any more?

2025-06-02 15:12 UTC, tabacitu commented on src/CrudPanelManager.php
> +    public function crud(CrudControllerContract $controller): CrudPanel
```suggestion
    private function getOrCreateCrudPanelInstance(CrudControllerContract $controller): CrudPanel
```

Let's make it private and rename it to `getOrCreateCrudPanelInstance()`

2025-06-02 15:18 UTC, tabacitu commented on src/CrudPanelManager.php
> +    public function crudFromController(string $controller, ?string $operation = null): CrudPanel
```suggestion
    public function setupCrudPanelInstance(string $controller, ?string $operation = null): CrudPanel
```

2025-06-02 15:20 UTC, tabacitu commented on src/CrudPanelManager.php
> +            $controller->initializeCrudController($primaryControllerRequest, $crud);
```suggestion
            $controller->initializeCrudPanel($primaryControllerRequest, $crud);
```

2025-06-02 15:22 UTC, tabacitu commented on src/CrudPanelManager.php
> +    }
```suggestion
    public function storeCrudPanel(string $controller, CrudPanel $crud): void
    {
        $this->cruds[$controller] = $crud;
    }
```

2025-06-02 15:23 UTC, tabacitu commented on src/CrudPanelManager.php
> +    public function hasCrudController(string $controller): bool
```suggestion
    public function hasCrudPanel(string $controller): bool
```

2025-06-02 15:23 UTC, tabacitu commented on src/CrudPanelManager.php
> +    public function getControllerCrud(string $controller): CrudPanel
```suggestion
    public function getActiveCrudPanel(string $fallbackController): CrudPanel
```

2025-06-02 15:28 UTC, tabacitu commented on src/CrudPanelManager.php
> +    public function getCrudPanel()
```suggestion
    public function identifyCrudPanel() : CrudPanel
```

2025-06-02 15:30 UTC, tabacitu commented on src/CrudPanelManager.php
> +    public function getCruds(): array
```suggestion
    public function getCrudPanels(): array
```

2025-06-05 09:05 UTC, tabacitu commented on src/BackpackServiceProvider.php
> +        Blade::component('datatable', Datatable::class);
We should probably use a component namespace... to avoid naming conflicts. Afaik this is doable with something like:

```php
        Blade::componentNamespace('Vendor\\Package\\View\\Components', 'bp');
```

Which would then make all our components start with `bp` instead of `x`. So it would be:

```html
<bp-datatable />
<bp-form />
<bp-menu-item />
```

Imho this is:
- good for avoiding name conflicts
- good for branding
- easy to do

So let's do it!

2025-06-05 09:11 UTC, tabacitu commented on src/app/Http/Controllers/Operations/ListOperation.php
> +
Hmmm it's a little fishy that ListOperation does something using the DataTable component... means there's a two-way binding here - the ListOperation uses the component, and the component uses the ListOperation...

Couldn't this have been done using hooks? I mean... that's why we added hooks in the first place, right? So people don't need to modify operations to make them do _extra stuff_.

2025-06-05 09:12 UTC, tabacitu commented on src/app/Http/Controllers/Operations/ListOperation.php
> +
If we don't have _default hooks_ perhaps we should add some _extra hooks_ for this operation alone - like `list:before_search` and `list:after_search`.

2025-06-05 09:23 UTC, tabacitu commented on src/CrudPanelManager.php
Omfg god - huuuge difference. Thanks @pxpm - now the class is crystal-clear in what it does.

I've taken the liberty to add comments to this class, to explain what everything does. Please go through the comments and change whetever you think is inexact, or not well explained.

2025-06-05 09:25 UTC, tabacitu commented on src/resources/views/crud/datatable/datatable.blade.php
@pxpm let's rename the directory, please.

Additionally, we should rename the directory of the PHP class too:

```diff
-Backpack\CRUD\app\Library\Datatable\Datatable;
+Backpack\CRUD\app\Library\Components\Datatable;
```

2025-06-05 10:02 UTC, tabacitu commented on src/resources/views/crud/datatable/datatable.blade.php
> +
Mentioned in https://github.com/Laravel-Backpack/CRUD/issues/5805 so let's close this

2025-06-05 10:06 UTC, tabacitu requested changes
One last push!

![sport-help-gif-by-nascar](https://github.com/user-attachments/assets/90e44b8d-30c9-4308-8391-d58d9cf0c879)

2025-06-05 15:29 UTC, pxpm commented on src/app/Http/Controllers/Operations/ListOperation.php
> +
The datatable can be defined in any operation/view so it would be impossible to determine where to register the hook. (the applyCachedSetup).

If you have any idea for this approach, please let me know, I am not seeing how we could do it.

2025-06-06 09:31 UTC, tabacitu commented on src/app/Http/Controllers/Operations/ListOperation.php
> +
Looking at `applyCachedSetupClosure()` I don't see many things there that are specific to the ListOperation (other than variable names). Seems like it's pretty "general-purpose" feature - if the cache has a setup closure, run it. So then... why have it in the DataTable component and not outside it, as a feature the Datatable component uses, but other components could use too?

The way I see it, with a separate `CachedSetup` feature (or whatever other name):
- the List operation would NOT depend on the Datatable component, it would just support the CachedSetup feature;
- other components can use the same functionality in the future (eg. Form component);

Would that make sense, Pedro?

2025-06-09 13:47 UTC, merged