[POC] "Agnostic" filters
Laravel-Backpack/CRUD pull request #5714
Opened 2024-11-06 16:55 UTC by pxpm

## WHY

### BEFORE - What was wrong? What was happening before this PR?

Filters were tightly coupled with the datatable making it impossible to use in a page that didn't had the datatable. 

### AFTER - What is happening after this PR?

Filters can be used in any page, and developer can configure the actions to perform when they are enabled/disabled. 

![image](https://github.com/user-attachments/assets/c8727000-056c-4c44-85c6-c1c19863b66a)

## HOW

### How did you achieve that, in technical terms?

transformed the filters_navbar into a component that can be reused. 
refactored the filters to emit events when they are changed.

### Is it a breaking change?

If you have `filters_navbar.blade.php` overwritten yes it is.

2024-11-27 17:04 UTC, susanu commented
**Off topic**: Would you consider adding support for global filters?
**Example**: A filter that will be displayed on all pages, lets say a date range filter.
On the cruds that have a date range filter, just take the values from the global one (if you set it this way).
**Use case**: You want to see statistics about last week on multiple cruds and don't want to set the date range every time you navigate to the crud.

Cheers!

2024-11-28 10:30 UTC, tabacitu commented
Hi @susanu - I think that's an interesting idea, but a very niche one. I see how it would be useful (I have a company select in one project too). But I don't think Backpack needs to help with it... it's ok for the dev to do it custom, since it's IS very custom, and particular to that project. We're not looking to add any "could-have" features, only "must-have" and "should-have". But it would make for a very interesting article - I'll give you that! Wanna write it?

2024-11-28 10:46 UTC, susanu commented
Hi @tabacitu,

I'm better at writing code than articles.
After v7 is released and filters can be reused in other places, i will submit a pull request, when time allows it, for this feature.

Cheers!

2024-12-02 12:16 UTC, pxpm commented
@susanu "theoretically" that's already possible. 

You can store the "global" filter (you can't use the native filters (yet!)) in a session variable, and add a middleware, or similar approach, that reads from that session variable and redirects the user to say `admin/invoices?date=2024-01-01`. If the `date` filter exist on the invoice crud, it will be automatically applied. 

Thanks for the suggestion, eagerly waiting for the PR 👍

2024-12-05 12:20 UTC, tabacitu requested changes
I agree with making it a component. I agree with the naming. Please redo the event names so it's `backpack:filters:clear` like I said in https://github.com/Laravel-Backpack/PRO/pull/296 too, merge `next` into this, test it, and give it back.

2024-12-05 12:20 UTC, tabacitu commented on src/resources/views/crud/inc/datatables_logic.blade.php
> +    document.addEventListener('Backpack:filters-cleared', function (event) {
```suggestion
    document.addEventListener('backpack:filters:cleared', function (event) {
```

2024-12-05 12:20 UTC, tabacitu commented on src/resources/views/crud/inc/datatables_logic.blade.php
> +    document.addEventListener('Backpack:filter-changed', function (event) {
```suggestion
    document.addEventListener('backpack:filter:changed', function (event) {
```

2024-12-20 09:20 UTC, tabacitu commented on src/resources/views/ui/components/filters-navbar.blade.php
What if we move all this code back to `crud::inc.filters_navbar`... and have the component blade file just do `@include('crud::inc.filters_navbar')`? That would give us both the benefit of having a component people can easily use... and make this less of a breaking change... right?

2024-12-20 09:46 UTC, tabacitu commented on src/resources/views/ui/components/filters-navbar.blade.php
Or waaaait. Since FILTERS are a PRO feature... wouldn't it make more sense to move the component and blade file.... inside the PRO package? 👀

2024-12-20 09:59 UTC, pxpm commented on src/resources/views/ui/components/filters-navbar.blade.php
In part it makes sense, the filters we have are all in PRO, but from other perspective "filters" != "filters framework". WDYM ? Well, `filters_navbar` it's the "suppport" for any filters, ours in PRO and any custom filters developers may have. So we ship the "filter framework" in the core, but we built our filters in PRO. 

I imagine a scenario where we develop a package and that package has their own filters (not using the pro ones), if we move this to PRO, that package must depend on PRO just to have the filters navbar where it can add the filters. Also, the `CrudFilter` class is in core not in PRO, so I think it makes sense to keep this on the core and not move it to pro. 

Your call 👍

2025-02-04 07:52 UTC, tabacitu commented on src/resources/views/ui/components/filters-navbar.blade.php
Ok you're right, let's the "filters framework" in CRUD. Good call, Pedro!

2025-02-04 08:51 UTC, tabacitu requested changes
Thanks a lot for this Pedro - I have a few notes.

Btw I agree with you with keeping the "_filters framework_" inside CRUD (not PRO). Good catch!

2025-02-04 08:51 UTC, tabacitu commented on src/resources/views/crud/inc/datatables_logic.blade.php
> +    // TODO: this needs to be agnostic per filter navbar as in the future hopefully we can have more than one
VERY good catch! Do we need to do this now, or can we do it later, as a non-breaking change? Cause it's a pretty big thing.

2025-02-04 08:51 UTC, tabacitu commented on src/resources/views/ui/components/filters-navbar.blade.php
> +<nav class="navbar navbar-expand-lg navbar-filters mb-0 py-0 shadow-none" id="{{ $id }}">
Let's move this back to `src/resources/views/crud/inc/filters_navbar.blade.php` please. At least for now.

Why? Because turning this from a blade file to a component... changes its scope. All the JS logic is no longer inside the `views/crud` namespace... it's inside the `views/ui` namespace. That's not good. The UI namespace isn't supposed to contain CRUD logic, it's supposed to contain blade files that a theme can (and should) customize, to make it looks different than the default. 

Don't get me wrong! I still LIKE and AGREE TO creating a component for the filters navbar! That is a GREAT way for us to introduce filtering bars that CAN be customized by each theme. I know people have been asking for that. But I don't want to get into that right now... Cause then we'll go down the rabbit hole of creating components for each filter as well... bleah! We'll get distracted.

Let's:
- [ ] take out the "component" bits out of this PR, and just have a simple blade file, that we include;
- [ ] create a new issue, for creating a `FiltersBar` component, so people can easily use it; put it on the v7 list, so we take care of it after we finish bigger issues;
- [ ] add a section to our docs, inside Filters > Tips and Tricks > "_How to add Filters to non-CRUD pages_", that explains how to do it;

2025-02-04 08:51 UTC, tabacitu commented on src/resources/views/crud/list.blade.php
> +          <x-backpack::filters-navbar :crud="$crud"/>
Does this blade file really need the `$crud`... or does it actually just require the `$filters`? Cause in the blade file the only mention is `$crud->filters`. Don't know which one would be better to pass... but i'm leaning towards `$filters`... Don't have a strong opinion on this so feel free to ignore it.

2025-02-04 08:51 UTC, tabacitu commented on src/app/View/Components/FiltersNavbar.php
> +<?php
I think this file should go away (or in a different PR). It doesn't do much anyway, just lets the developer use the `<x-backpack::filters-navbar :crud="$crud"/>` syntax and adds an ID.

Read on for more. I have a logic, I promise!

2025-02-07 08:56 UTC, merged