Update datatables scripts
Laravel-Backpack/CRUD pull request #5724
Opened 2024-11-25 19:57 UTC by pxpm

## WHY

### BEFORE - What was wrong? What was happening before this PR?

We were lagging ALOT in datatables versions. Major improvements and bug fixes had been made in the meanwhile, and we were not benefiting from it. 

The reason was the amount of hours I need to spend to track and fix the issues that popped up just by bumping the datatables version in the cdn url. It's done 👍 

### AFTER - What is happening after this PR?

We are on the bleeding egde of datatables, future upgrades will be WAY easier. It looks to me that the table performs a little better. 

### Is it a breaking change?

I don't think so 🤷‍♂️

2024-11-25 20:27 UTC, pxpm commented on src/resources/views/crud/inc/datatables_logic.blade.php
> +        console.log('column-visibility.dt');
```suggestion
```

2024-11-25 20:27 UTC, pxpm commented on src/resources/views/crud/inc/datatables_logic.blade.php
> +            console.log('responsive-resize', crud.table.responsive.hasHidden());
```suggestion
```

2024-12-05 11:15 UTC, tabacitu commented
@pxpm I can confirm this PR fixes the alignment issue (omfg finally!), and it works for most CRUDS. 

But I noticed it also breaks a few CRUDs in our demo - Invoices CRUD, Pets CRUD:

![CleanShot 2024-12-05 at 13 14 21@2x](https://github.com/user-attachments/assets/aa7fcad9-1264-4c04-989a-38d1fbbccdc8)

2025-02-04 09:10 UTC, tabacitu commented on src/resources/views/crud/list.blade.php
>    {{-- DATA TABLES --}}
I'm bringing sexy back!!

![sexy-justin-timberlake-gif](https://github.com/user-attachments/assets/cd9d03bf-c066-4241-8aed-6c423840aa56)

YEAH!

```suggestion
  {{-- DATA TABLES --}}
    @basset('https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.min.css')
    @basset("https://cdn.datatables.net/responsive/3.0.3/css/responsive.dataTables.min.css")
    @basset('https://cdn.datatables.net/fixedheader/4.0.1/css/fixedHeader.dataTables.min.css')
```

2025-02-04 09:21 UTC, tabacitu commented on src/resources/views/crud/inc/datatables_logic.blade.php
>        // move search bar
Search bar no longer works for me... it doesn't actually search - no network request, no error, nothing  👀


https://github.com/user-attachments/assets/d8311a1a-fab0-4f89-9ae5-5f1e6df79d01

2025-02-05 12:13 UTC, pxpm commented
@tabacitu I've removed the `@push()` to the scripts since they are already included in the `after_scripts` section. 

I've just kept the includes on the same file, because not having datatable assets in the list blade, allow us to include the table (in a near future) in other pages that are not related with the `list.blade.php`. 

I've also fixed the search functionality.

2025-02-07 07:50 UTC, tabacitu requested changes
Can confirm it works now! Thanks Pedro.

But there are some differences in looks here, between the old and new. The changes triggered some changes in the footer that makes it looks like there's be no care given to it. Here's what I mean:

![CleanShot 2025-02-07 at 09 45 33](https://github.com/user-attachments/assets/65d73e7a-c24a-486e-87d3-74ca9c7def20)

And here are a few things that stand out to me right away:

![CleanShot 2025-02-07 at 09 46 39@2x](https://github.com/user-attachments/assets/32b85d48-1f93-4b2a-ba26-ba869237fd6f)

Please polish these last things, then merge it.

2025-02-07 14:19 UTC, pxpm commented
It's done @tabacitu please give it the last look to make sure I didn't forget to polish anything. From my POV it looks ok 👍

2025-05-06 15:28 UTC, closed without merging

2025-05-06 15:28 UTC, pxpm commented
super seeded by #5688